# GoReleaser configuration for DittoFS
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test -short ./...

builds:
  - id: dfs
    main: ./cmd/dfs/main.go
    binary: dfs

    env:
      - CGO_ENABLED=0  # Static binaries

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"  # ARMv7 for Raspberry Pi, etc.

    # Ignore combinations that don't make sense
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

    ldflags:
      # Inject version info
      - -s -w  # Strip debug info
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

  - id: dfsctl
    main: ./cmd/dfsctl/main.go
    binary: dfsctl

    env:
      - CGO_ENABLED=0  # Static binaries

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"  # ARMv7 for Raspberry Pi, etc.

    # Ignore combinations that don't make sense
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

    ldflags:
      # Inject version info
      - -s -w  # Strip debug info
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: dfs-archive
    builds:
      - dfs
    name_template: >-
      dfs_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

  - id: dfsctl-archive
    builds:
      - dfsctl
    name_template: >-
      dfsctl_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - merges
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# Docker images configuration
dockers:
  # AMD64 image
  - id: dfs-amd64
    goos: linux
    goarch: amd64
    use: buildx
    image_templates:
      - "marmos91c/dittofs:{{ .Tag }}-amd64"
      - "marmos91c/dittofs:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=DittoFS"
      - "--label=org.opencontainers.image.description=Modular virtual filesystem with pluggable storage backends"
      - "--label=org.opencontainers.image.url=https://github.com/marmos91/dittofs"
      - "--label=org.opencontainers.image.source=https://github.com/marmos91/dittofs"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    dockerfile: Dockerfile.goreleaser

  # ARM64 image
  - id: dfs-arm64
    goos: linux
    goarch: arm64
    use: buildx
    image_templates:
      - "marmos91c/dittofs:{{ .Tag }}-arm64"
      - "marmos91c/dittofs:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=DittoFS"
      - "--label=org.opencontainers.image.description=Modular virtual filesystem with pluggable storage backends"
      - "--label=org.opencontainers.image.url=https://github.com/marmos91/dittofs"
      - "--label=org.opencontainers.image.source=https://github.com/marmos91/dittofs"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    dockerfile: Dockerfile.goreleaser

# Docker manifest for multi-arch images
docker_manifests:
  - name_template: "marmos91c/dittofs:{{ .Tag }}"
    image_templates:
      - "marmos91c/dittofs:{{ .Tag }}-amd64"
      - "marmos91c/dittofs:{{ .Tag }}-arm64"

  - name_template: "marmos91c/dittofs:latest"
    image_templates:
      - "marmos91c/dittofs:latest-amd64"
      - "marmos91c/dittofs:latest-arm64"

  # Version-specific manifests for major and minor versions
  - name_template: "marmos91c/dittofs:v{{ .Major }}"
    image_templates:
      - "marmos91c/dittofs:{{ .Tag }}-amd64"
      - "marmos91c/dittofs:{{ .Tag }}-arm64"

  - name_template: "marmos91c/dittofs:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "marmos91c/dittofs:{{ .Tag }}-amd64"
      - "marmos91c/dittofs:{{ .Tag }}-arm64"

# Homebrew tap formulae
brews:
  - name: dfs
    ids:
      - dfs-archive
    repository:
      owner: marmos91
      name: homebrew-tap
      directory: Formula
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_msg_template: "Brew formula update for dfs version {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/marmos91/dittofs"
    description: "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "dfs"
      generate_completions_from_executable(bin/"dfs", "completion")
    test: |
      system bin/"dfs", "version", "--short"

  - name: dfsctl
    ids:
      - dfsctl-archive
    repository:
      owner: marmos91
      name: homebrew-tap
      directory: Formula
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_msg_template: "Brew formula update for dfsctl version {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/marmos91/dittofs"
    description: "DittoFS CLI client — remote management for DittoFS servers"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "dfsctl"
      generate_completions_from_executable(bin/"dfsctl", "completion")
    test: |
      system bin/"dfsctl", "version", "--short"

# Scoop bucket manifests for Windows distribution
scoops:
  - name: dfs
    ids:
      - dfs-archive
    repository:
      owner: marmos91
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    commit_msg_template: "Scoop update for dfs version {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/marmos91/dittofs"
    description: "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
    license: "MIT"
    skip_upload: auto

  - name: dfsctl
    ids:
      - dfsctl-archive
    repository:
      owner: marmos91
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    commit_msg_template: "Scoop update for dfsctl version {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/marmos91/dittofs"
    description: "DittoFS CLI client — remote management for DittoFS servers"
    license: "MIT"
    skip_upload: auto

release:
  github:
    owner: marmos91
    name: dittofs

  # Prerelease detection
  prerelease: auto

  # Release notes
  header: |
    ## DittoFS {{ .Tag }}

    A modular virtual filesystem that decouples file interfaces from storage backends.

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew tap marmos91/tap
    brew install marmos91/tap/dfs      # Server daemon
    brew install marmos91/tap/dfsctl   # Client CLI
    ```

    **Scoop (Windows):**
    ```powershell
    scoop bucket add marmos91 https://github.com/marmos91/scoop-bucket
    scoop install dfs       # Server daemon
    scoop install dfsctl    # Client CLI
    ```

    **Binary Download:**
    ```bash
    # dfs (server daemon)
    # Linux (x86_64)
    curl -sfL https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfs_{{ .Version }}_Linux_x86_64.tar.gz | tar xz

    # macOS (Apple Silicon)
    curl -sfL https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfs_{{ .Version }}_Darwin_arm64.tar.gz | tar xz

    # macOS (Intel)
    curl -sfL https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfs_{{ .Version }}_Darwin_x86_64.tar.gz | tar xz

    # Windows (x86_64)
    Invoke-WebRequest -Uri "https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfs_{{ .Version }}_Windows_x86_64.zip" -OutFile dfs.zip; Expand-Archive dfs.zip -DestinationPath .; Remove-Item dfs.zip

    # Windows (arm64)
    Invoke-WebRequest -Uri "https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfs_{{ .Version }}_Windows_arm64.zip" -OutFile dfs.zip; Expand-Archive dfs.zip -DestinationPath .; Remove-Item dfs.zip

    # dfsctl (client CLI)
    # Linux (x86_64)
    curl -sfL https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfsctl_{{ .Version }}_Linux_x86_64.tar.gz | tar xz

    # macOS (Apple Silicon)
    curl -sfL https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfsctl_{{ .Version }}_Darwin_arm64.tar.gz | tar xz

    # macOS (Intel)
    curl -sfL https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfsctl_{{ .Version }}_Darwin_x86_64.tar.gz | tar xz

    # Windows (x86_64)
    Invoke-WebRequest -Uri "https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfsctl_{{ .Version }}_Windows_x86_64.zip" -OutFile dfsctl.zip; Expand-Archive dfsctl.zip -DestinationPath .; Remove-Item dfsctl.zip

    # Windows (arm64)
    Invoke-WebRequest -Uri "https://github.com/marmos91/dittofs/releases/download/{{ .Tag }}/dfsctl_{{ .Version }}_Windows_arm64.zip" -OutFile dfsctl.zip; Expand-Archive dfsctl.zip -DestinationPath .; Remove-Item dfsctl.zip
    ```

    **Docker:**
    ```bash
    # Pull the latest image
    docker pull marmos91c/dittofs:{{ .Tag }}

    # Run with a config file
    docker run -d \
      -p 12049:12049 \
      -p 12445:12445 \
      -p 8080:8080 \
      -v /path/to/config.yaml:/config/config.yaml:ro \
      -v dittofs-data:/data \
      marmos91c/dittofs:{{ .Tag }}
    ```

  footer: |
    ---

    **Full Changelog**: https://github.com/marmos91/dittofs/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Verifying Checksums

    ```bash
    sha256sum -c checksums.txt
    ```

    ### Docker Images

    Multi-architecture images are available for `linux/amd64` and `linux/arm64`:
    - `marmos91c/dittofs:{{ .Tag }}` - This specific version
    - `marmos91c/dittofs:latest` - Latest stable release
    - `marmos91c/dittofs:v{{ .Major }}` - Latest v{{ .Major }}.x.x
    - `marmos91c/dittofs:v{{ .Major }}.{{ .Minor }}` - Latest v{{ .Major }}.{{ .Minor }}.x
