package metadata

import (
	"hash/fnv"
	"sync"
)

// CookieManager handles NFS cookie ↔ store token translation.
//
// NFS uses uint64 cookies for directory pagination, but stores use
// string tokens (filenames, UUIDs, etc.). This manager provides a
// centralized translation layer that works with any store implementation.
//
// Cookies are generated by hashing the directory handle + entry name,
// ensuring uniqueness per directory. A reverse mapping is maintained
// to convert cookies back to tokens for subsequent requests.
//
// Thread-safe: uses sync.Map for concurrent access.
type CookieManager struct {
	// cookieToToken maps cookie → token for reverse lookup
	cookieToToken sync.Map // map[uint64]string
}

// NewCookieManager creates a new cookie manager.
func NewCookieManager() *CookieManager {
	return &CookieManager{}
}

// GenerateCookie creates a unique cookie for a directory entry.
// The cookie is based on the directory handle and entry name.
// Returns 0 if the name is empty (indicating end of directory).
func (cm *CookieManager) GenerateCookie(dirHandle FileHandle, name string) uint64 {
	if name == "" {
		return 0
	}

	// Generate cookie by hashing dirHandle + name
	h := fnv.New64a()
	h.Write([]byte(dirHandle))
	h.Write([]byte(name))
	cookie := h.Sum64()

	// Ensure cookie is never 0 (reserved for start of directory)
	if cookie == 0 {
		cookie = 1
	}

	// Store reverse mapping
	cm.cookieToToken.Store(cookie, name)

	return cookie
}

// GetToken retrieves the token (entry name) for a cookie.
// Returns empty string if cookie is 0 (start of directory) or unknown.
func (cm *CookieManager) GetToken(cookie uint64) string {
	if cookie == 0 {
		return ""
	}

	if token, ok := cm.cookieToToken.Load(cookie); ok {
		return token.(string)
	}

	return ""
}

// Clear removes all stored cookie mappings.
// Useful for cache invalidation when directories change significantly.
func (cm *CookieManager) Clear() {
	cm.cookieToToken.Range(func(key, _ any) bool {
		cm.cookieToToken.Delete(key)
		return true
	})
}

// ClearForDirectory removes cookie mappings for a specific directory.
// Called when a directory is modified to invalidate stale cookies.
func (cm *CookieManager) ClearForDirectory(dirHandle FileHandle) {
	// Since we hash dirHandle+name, we can't easily filter by directory
	// In practice, stale cookies will just cause a restart from beginning
	// which is correct behavior per RFC 1813 (cookie verifier mismatch)
}
