package handlers

import (
	"context"
	"fmt"
	"sync"

	"github.com/marmos91/dittofs/internal/adapter/smb/types"
	"github.com/marmos91/dittofs/internal/logger"
)

// AsyncCreateCompleteCallback delivers the final async CREATE response for a
// request that was parked on a lease break. The callback is responsible for
// stamping FlagAsync + AsyncId, signing, and releasing the async credit slot.
// The body is the encoded SMB2 CREATE response body (or nil for error status,
// in which case SendAsyncCompletionResponse substitutes MakeErrorBody).
type AsyncCreateCompleteCallback func(sessionID, messageID, asyncId uint64, status types.Status, body []byte) error

// PendingCreate tracks a CREATE request parked on a lease break. It holds the
// identifiers needed to locate the entry on CANCEL / session teardown and the
// cancel function that tears down the resume goroutine's wait.
type PendingCreate struct {
	// Request identification.
	ConnID    uint64
	SessionID uint64
	MessageID uint64
	AsyncId   uint64

	// Cancel tears down the resume goroutine's break-wait (via context cancel)
	// so CANCEL / session teardown can unblock it promptly.
	Cancel context.CancelFunc

	// Callback delivers the final SMB2 CREATE response. Invoked by the resume
	// goroutine on normal completion OR by the registry on CANCEL (with
	// StatusCancelled + nil body). Releases the async slot as part of its work.
	Callback AsyncCreateCompleteCallback

	// started is closed by MarkStarted once the dispatch layer has finalized
	// the Callback assignment for this entry. The resume goroutine MUST wait
	// on it before invoking Callback. Without this gate, a fast localhost
	// break ACK can let the resume goroutine fire the original callback
	// BEFORE the compound dispatcher has had a chance to swap in the
	// continue-compound wrapper, sending the CREATE response standalone and
	// stranding the remaining compound subcommands (smbtorture
	// smb2.compound.compound-break IO_TIMEOUT, observed flake).
	//
	// CANCEL / session-teardown paths invoke Callback directly without going
	// through the resume goroutine, so they do NOT need to wait on this gate.
	started     chan struct{}
	startedOnce sync.Once
}

// createMsgKey scopes a MessageID to its connection, since SMB2 MessageIDs are
// per-connection.
type createMsgKey struct {
	ConnID    uint64
	MessageID uint64
}

// Secondary-index slots for PendingCreateRegistry, in configured order.
const (
	createIdxMsgKey = iota
)

// Bucket-index slots for PendingCreateRegistry, in configured order.
const (
	createBucketSession = iota
)

// MaxPendingCreates caps concurrent parked CREATEs per server to protect the
// process from runaway clients. Picked to match MaxPendingWatches.
const MaxPendingCreates = 4096

// ErrTooManyPendingCreates is returned when the global pending-CREATE limit
// would be exceeded.
var ErrTooManyPendingCreates = fmt.Errorf("too many pending CREATEs (max %d)", MaxPendingCreates)

// ErrDuplicateAsyncId is returned when Register is called with an AsyncId that
// is already in the registry. AsyncIds are generated by an atomic counter on
// the Handler, so a collision implies either counter exhaustion (2^64 opens)
// or a programming error. Treat it as a programming error and refuse to evict
// the prior entry — the caller owns releasing its own async slot.
var ErrDuplicateAsyncId = fmt.Errorf("duplicate AsyncId in PendingCreateRegistry")

// ErrDuplicateMessageID is returned when Register is called with a
// (ConnID, MessageID) pair that is already in the registry. SMB2 clients must
// not reuse an in-flight MessageID on the same connection, so a collision
// implies either client misbehavior or server-side state corruption. Refuse
// the new registration rather than silently evicting the prior entry.
var ErrDuplicateMessageID = fmt.Errorf("duplicate (ConnID, MessageID) in PendingCreateRegistry")

// PendingCreateRegistry indexes pending CREATEs by three keys: per-connection
// MessageID (for synchronous CANCEL), AsyncId (for async-flagged CANCEL), and
// SessionID (for session teardown). Thread-safe.
//
// An entry is removed exactly once: either by the resume goroutine after it
// delivers the final response (via Unregister) or by CANCEL / teardown (via
// UnregisterByMessageID / UnregisterByAsyncId / UnregisterAllForSession).
// The resume goroutine must check whether its entry is still registered before
// sending, so a concurrent CANCEL does not produce a duplicate response for
// the same MessageID.
type PendingCreateRegistry struct {
	reg *pendingRegistry[PendingCreate]
}

// NewPendingCreateRegistry builds an empty registry.
func NewPendingCreateRegistry() *PendingCreateRegistry {
	return &PendingCreateRegistry{
		reg: newPendingRegistry(registryConfig[PendingCreate]{
			asyncID: func(p *PendingCreate) uint64 { return p.AsyncId },
			indexes: []keyFunc[PendingCreate]{
				func(p *PendingCreate) any {
					return createMsgKey{ConnID: p.ConnID, MessageID: p.MessageID}
				},
			},
			buckets: []keyFunc[PendingCreate]{
				func(p *PendingCreate) any { return p.SessionID },
			},
			maxOps: MaxPendingCreates,
		}),
	}
}

// Register inserts a pending CREATE. Returns an error on overflow or if the
// entry would collide with an existing (ConnID, MessageID) or AsyncId; in all
// failure cases the registry is left untouched and the caller owns releasing
// its reserved async slot.
func (r *PendingCreateRegistry) Register(p *PendingCreate) error {
	r.reg.mu.Lock()
	defer r.reg.mu.Unlock()

	if len(r.reg.byAsyncID) >= r.reg.maxOps {
		return ErrTooManyPendingCreates
	}
	if r.reg.lookupLocked(createIdxMsgKey, createMsgKey{ConnID: p.ConnID, MessageID: p.MessageID}) != nil {
		return ErrDuplicateMessageID
	}
	if _, dup := r.reg.byAsyncID[p.AsyncId]; dup {
		return ErrDuplicateAsyncId
	}

	r.reg.insertLocked(p)

	logger.Debug("PendingCreateRegistry: registered",
		"connID", p.ConnID,
		"sessionID", p.SessionID,
		"messageID", p.MessageID,
		"asyncId", p.AsyncId,
		"total", len(r.reg.byAsyncID))
	return nil
}

// Unregister removes a pending CREATE by AsyncId without calling Cancel. Used
// by the resume goroutine AFTER it has successfully delivered the final
// response. Returns the removed entry, or nil if it was already unregistered
// (e.g. by a concurrent CANCEL).
func (r *PendingCreateRegistry) Unregister(asyncId uint64) *PendingCreate {
	return r.reg.unregisterByAsyncID(asyncId)
}

// UnregisterByMessageID removes a pending CREATE matching (connID, messageID)
// and invokes its Cancel closure to unblock the resume goroutine. Returns the
// removed entry, or nil if none matched. Used by synchronous SMB2_CANCEL.
func (r *PendingCreateRegistry) UnregisterByMessageID(connID, messageID uint64) *PendingCreate {
	p := r.reg.unregisterByIndex(createIdxMsgKey, createMsgKey{ConnID: connID, MessageID: messageID})
	if p == nil {
		return nil
	}
	// Release the started gate so any resume goroutine racing the cancel
	// path past its Unregister check will not deadlock waiting on dispatch
	// to MarkStarted (CANCEL/teardown bypass the dispatcher).
	markStarted(p)
	if p.Cancel != nil {
		p.Cancel()
	}
	return p
}

// UnregisterByAsyncId removes a pending CREATE matching asyncId and invokes
// its Cancel closure. Used by async-flagged SMB2_CANCEL.
func (r *PendingCreateRegistry) UnregisterByAsyncId(asyncId uint64) *PendingCreate {
	p := r.reg.unregisterByAsyncID(asyncId)
	if p != nil {
		markStarted(p)
		if p.Cancel != nil {
			p.Cancel()
		}
	}
	return p
}

// UnregisterAllForSession removes and returns every pending CREATE associated
// with sessionID, invoking Cancel on each. Used by session teardown to unblock
// goroutines before the session state they depend on is freed.
func (r *PendingCreateRegistry) UnregisterAllForSession(sessionID uint64) []*PendingCreate {
	removed := r.reg.unregisterBucket(createBucketSession, sessionID)
	for _, p := range removed {
		markStarted(p)
		if p.Cancel != nil {
			p.Cancel()
		}
	}
	return removed
}

// ReplaceCallback atomically replaces the Callback of a pending CREATE
// identified by asyncId. Used by the compound processor to redirect the
// CREATE's completion from sending a standalone response to continuing
// compound processing (smbtorture compound_async.getinfo_middle). Returns
// true if the entry was found and updated, false if it was already gone
// (e.g. concurrently cancelled).
func (r *PendingCreateRegistry) ReplaceCallback(asyncId uint64, cb AsyncCreateCompleteCallback) bool {
	r.reg.mu.Lock()
	defer r.reg.mu.Unlock()
	p, ok := r.reg.byAsyncID[asyncId]
	if !ok {
		return false
	}
	p.Callback = cb
	return true
}

// MarkStarted releases the resume goroutine for the pending CREATE identified
// by asyncId so it may invoke its (possibly replaced) Callback. Callers MUST
// invoke MarkStarted after they have finished any callback reassignment
// (e.g. compound dispatcher's ReplaceCallback). Idempotent: safe to call
// even after the entry has been unregistered by CANCEL / teardown.
//
// Returns true if the gate was successfully signalled, false if the entry
// was no longer in the registry. The latter is not an error — CANCEL /
// teardown already drove the callback synchronously and the gate is moot.
func (r *PendingCreateRegistry) MarkStarted(asyncId uint64) bool {
	r.reg.mu.Lock()
	p, ok := r.reg.byAsyncID[asyncId]
	r.reg.mu.Unlock()
	if !ok {
		return false
	}
	markStarted(p)
	return true
}

// markStarted closes the started gate exactly once. Called both by the
// public MarkStarted (dispatch-layer release) and by internal cleanup paths
// (CANCEL / teardown) that pull entries directly and need to unblock any
// resume goroutine still parked on the wait — without the unblock, the
// goroutine would leak when CANCEL runs after MarkStarted's window closes.
func markStarted(p *PendingCreate) {
	if p == nil || p.started == nil {
		return
	}
	p.startedOnce.Do(func() { close(p.started) })
}

// Len returns the number of pending CREATEs.
func (r *PendingCreateRegistry) Len() int {
	return r.reg.Len()
}
