package memory

import (
	"bytes"
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"lukechampine.com/blake3"

	"github.com/marmos91/dittofs/pkg/blockstore"
	"github.com/marmos91/dittofs/pkg/blockstore/chunker"
	"github.com/marmos91/dittofs/pkg/blockstore/local"
)

// Compile-time interface satisfaction check. Plan 17-07 restored the
// assertion after MemoryStore gained the BlockStoreAppend-contributed
// methods (Put/Get/GetRange/Has/Delete/Head/Walk/AppendWrite/DeleteLog).
var _ local.LocalStore = (*MemoryStore)(nil)

// ErrStoreClosed is an alias for blockstore.ErrStoreClosed for backward compatibility.
var ErrStoreClosed = blockstore.ErrStoreClosed

// memBlock holds data for a single block in memory (legacy
// per-payloadID-per-block surface — used by the transitional admin
// methods ReadAt / WriteAt / Flush / GetBlockData / IsBlockLocal /
// WriteFromRemote / DeleteAllBlockFiles slated for deletion in Phase
// 18).
type memBlock struct {
	data     []byte
	dataSize uint32
	dirty    bool
	state    blockstore.BlockState
}

// casEntry is a single content-addressed chunk plus its metadata.
type casEntry struct {
	data         []byte
	lastModified time.Time
}

// MemoryStore is a pure in-memory implementation of local.LocalStore.
// All data lives in maps; nothing touches disk. Useful for testing and
// ephemeral configurations.
//
// Phase 17 added a CAS-keyed surface (cas / appendLogs / tombstones)
// alongside the legacy per-block surface (blocks / files) so the store
// satisfies blockstore.BlockStoreAppend and the narrowed
// local.LocalStore admin-superset simultaneously.
type MemoryStore struct {
	mu sync.RWMutex

	// blocks stores legacy block data keyed by "payloadID/blockIdx".
	blocks map[string]*memBlock

	// files tracks file sizes (payloadID -> size).
	files map[string]uint64

	// cas stores content-addressed chunks for the BlockStore surface.
	cas map[blockstore.ContentHash]casEntry

	// appendLogs buffers per-payload AppendWrite data; the synchronous
	// rollup runs FastCDC over the consolidated buffer at every
	// AppendWrite (cheap for an in-memory test fixture).
	appendLogs map[string]*appendLog

	// tombstones marks payloadIDs whose append log was deleted.
	tombstones map[string]struct{}

	closed          bool
	evictionEnabled bool
}

// appendLog is the per-payload write-absorber buffer. AppendWrite
// extends `buf` (sparse-filling gaps with zeros when offset > len) and
// the synchronous rollup chunks the whole buffer.
type appendLog struct {
	buf []byte
}

// New creates a new MemoryStore.
func New() *MemoryStore {
	return &MemoryStore{
		blocks:          make(map[string]*memBlock),
		files:           make(map[string]uint64),
		cas:             make(map[blockstore.ContentHash]casEntry),
		appendLogs:      make(map[string]*appendLog),
		tombstones:      make(map[string]struct{}),
		evictionEnabled: true,
	}
}

// memBlockKey returns the map key for a legacy per-block entry.
// Format: "<payloadID>/<blockIdx>". Internal to memory.go after the
// blockstore.FormatStoreKey helper was deleted in Phase 17.
func memBlockKey(payloadID string, blockIdx uint64) string {
	return payloadID + "/" + strconv.FormatUint(blockIdx, 10)
}

// keyBelongsToFile reports whether a legacy memBlockKey belongs to the
// given payloadID. Internal to memory.go after the
// blockstore.KeyBelongsToFile helper was deleted in Phase 17.
func keyBelongsToFile(key, payloadID string) bool {
	prefix := payloadID + "/"
	return strings.HasPrefix(key, prefix)
}

// parseBlockIdx extracts the blockIdx from a legacy memBlockKey
// generated by memBlockKey above. Returns 0 if the key is malformed
// (matches the historical blockstore.ParseBlockIdx tolerance).
func parseBlockIdx(key, payloadID string) uint64 {
	prefix := payloadID + "/"
	if !strings.HasPrefix(key, prefix) {
		return 0
	}
	idx, err := strconv.ParseUint(key[len(prefix):], 10, 64)
	if err != nil {
		return 0
	}
	return idx
}

// ReadAt reads data from the in-memory store at the specified offset into dest.
//
// Deprecated: removed in Phase 18 (Syncer simplification rewrites these consumers onto BlockStore.Put/Get/Walk).
func (s *MemoryStore) ReadAt(_ context.Context, payloadID string, dest []byte, offset uint64) (bool, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if s.closed {
		return false, ErrStoreClosed
	}

	if len(dest) == 0 {
		return true, nil
	}

	remaining := dest
	currentOffset := offset

	for len(remaining) > 0 {
		blockIdx := currentOffset / blockstore.BlockSize
		blockOffset := uint32(currentOffset % blockstore.BlockSize)

		readLen := uint32(len(remaining))
		spaceInBlock := uint32(blockstore.BlockSize) - blockOffset
		if readLen > spaceInBlock {
			readLen = spaceInBlock
		}

		key := memBlockKey(payloadID, blockIdx)
		mb, ok := s.blocks[key]
		if !ok || mb.data == nil {
			return false, nil // Block not available
		}
		if blockOffset+readLen > mb.dataSize {
			return false, nil // Beyond written data
		}

		copy(remaining[:readLen], mb.data[blockOffset:blockOffset+readLen])
		remaining = remaining[readLen:]
		currentOffset += uint64(readLen)
	}

	return true, nil
}

// GetFileSize returns the tracked file size.
func (s *MemoryStore) GetFileSize(_ context.Context, payloadID string) (uint64, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	size, ok := s.files[payloadID]
	return size, ok
}

// IsBlockLocal checks if a specific block is available in the store.
//
// Deprecated: removed in Phase 18.
func (s *MemoryStore) IsBlockLocal(_ context.Context, payloadID string, blockIdx uint64) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	key := memBlockKey(payloadID, blockIdx)
	mb, ok := s.blocks[key]
	return ok && mb.data != nil
}

// GetBlockData returns the raw data for a specific block.
//
// Deprecated: removed in Phase 18.
func (s *MemoryStore) GetBlockData(_ context.Context, payloadID string, blockIdx uint64) ([]byte, uint32, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if s.closed {
		return nil, 0, ErrStoreClosed
	}

	key := memBlockKey(payloadID, blockIdx)
	mb, ok := s.blocks[key]
	if !ok || mb.data == nil || mb.dataSize == 0 {
		return nil, 0, blockstore.ErrBlockNotFound
	}

	data := make([]byte, mb.dataSize)
	copy(data, mb.data[:mb.dataSize])
	return data, mb.dataSize, nil
}

// Put writes data under the key derived from hash. Idempotent on
// (hash, identical bytes).
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) Put(_ context.Context, hash blockstore.ContentHash, data []byte) error {
	if hash.IsZero() {
		return fmt.Errorf("blockstore.memory: Put with zero hash")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return ErrStoreClosed
	}
	if existing, ok := s.cas[hash]; ok {
		if bytes.Equal(existing.data, data) {
			return nil
		}
		// Same-hash different-bytes is undefined per the contract; we
		// adopt the "no-op on first-write-wins" stance (the conformance
		// suite only asserts the same-bytes case).
		return nil
	}
	buf := make([]byte, len(data))
	copy(buf, data)
	s.cas[hash] = casEntry{data: buf, lastModified: time.Now()}
	return nil
}

// Get returns the CAS chunk addressed by hash. The returned slice is a
// fresh copy — backends MUST NOT alias internal storage.
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) Get(_ context.Context, hash blockstore.ContentHash) ([]byte, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed {
		return nil, ErrStoreClosed
	}
	entry, ok := s.cas[hash]
	if !ok {
		return nil, blockstore.ErrChunkNotFound
	}
	out := make([]byte, len(entry.data))
	copy(out, entry.data)
	return out, nil
}

// GetRange returns a byte sub-range of the chunk addressed by hash.
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) GetRange(_ context.Context, hash blockstore.ContentHash, offset, length int64) ([]byte, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed {
		return nil, ErrStoreClosed
	}
	if offset < 0 {
		return nil, fmt.Errorf("blockstore.memory: GetRange: negative offset %d", offset)
	}
	if length <= 0 {
		return nil, fmt.Errorf("blockstore.memory: GetRange: non-positive length %d", length)
	}
	entry, ok := s.cas[hash]
	if !ok {
		return nil, blockstore.ErrChunkNotFound
	}
	size := int64(len(entry.data))
	if offset >= size {
		return nil, fmt.Errorf("blockstore.memory: GetRange: offset %d beyond size %d", offset, size)
	}
	if offset+length > size {
		length = size - offset
	}
	out := make([]byte, length)
	copy(out, entry.data[offset:offset+length])
	return out, nil
}

// Has reports whether the store currently holds an object addressed by hash.
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) Has(_ context.Context, hash blockstore.ContentHash) (bool, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed {
		return false, ErrStoreClosed
	}
	_, ok := s.cas[hash]
	return ok, nil
}

// Delete removes the object addressed by hash. Idempotent.
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) Delete(_ context.Context, hash blockstore.ContentHash) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return ErrStoreClosed
	}
	delete(s.cas, hash)
	return nil
}

// Head returns Meta for the object addressed by hash.
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) Head(_ context.Context, hash blockstore.ContentHash) (blockstore.Meta, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed {
		return blockstore.Meta{}, ErrStoreClosed
	}
	entry, ok := s.cas[hash]
	if !ok {
		return blockstore.Meta{}, blockstore.ErrChunkNotFound
	}
	return blockstore.Meta{
		Size:         int64(len(entry.data)),
		LastModified: entry.lastModified,
	}, nil
}

// Walk enumerates every CAS object in deterministic hash order. The
// callback may return blockstore.ErrStopWalk for clean early exit.
//
// Implements blockstore.BlockStore.
func (s *MemoryStore) Walk(ctx context.Context, fn func(hash blockstore.ContentHash, meta blockstore.Meta) error) error {
	s.mu.RLock()
	if s.closed {
		s.mu.RUnlock()
		return ErrStoreClosed
	}
	// Snapshot under read lock to avoid holding it across user callback.
	hashes := make([]blockstore.ContentHash, 0, len(s.cas))
	for h := range s.cas {
		hashes = append(hashes, h)
	}
	snapshot := make(map[blockstore.ContentHash]casEntry, len(s.cas))
	for h, e := range s.cas {
		snapshot[h] = e
	}
	s.mu.RUnlock()

	sort.Slice(hashes, func(i, j int) bool {
		return bytes.Compare(hashes[i][:], hashes[j][:]) < 0
	})
	for _, h := range hashes {
		if err := ctx.Err(); err != nil {
			return err
		}
		entry := snapshot[h]
		meta := blockstore.Meta{Size: int64(len(entry.data)), LastModified: entry.lastModified}
		if err := fn(h, meta); err != nil {
			if err == blockstore.ErrStopWalk {
				return nil
			}
			return fmt.Errorf("walk halted at %s: %w", h, err)
		}
	}
	return nil
}

// AppendWrite stages random-offset bytes for payloadID into a
// per-file in-memory buffer and synchronously runs FastCDC over the
// consolidated buffer, emitting any newly-discovered chunks via the
// internal CAS map. Backends with on-disk logs use an asynchronous
// rollup goroutine; the in-memory backend runs it inline because the
// test surface needs deterministic post-AppendWrite Walk visibility.
//
// Implements blockstore.BlockStoreAppend.
func (s *MemoryStore) AppendWrite(_ context.Context, payloadID string, data []byte, offset uint64) error {
	if len(data) == 0 {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return ErrStoreClosed
	}
	if _, tombstoned := s.tombstones[payloadID]; tombstoned {
		return fmt.Errorf("blockstore.memory: AppendWrite on tombstoned payload %q", payloadID)
	}
	log, ok := s.appendLogs[payloadID]
	if !ok {
		log = &appendLog{}
		s.appendLogs[payloadID] = log
	}
	end := offset + uint64(len(data))
	if uint64(len(log.buf)) < end {
		grown := make([]byte, end)
		copy(grown, log.buf)
		log.buf = grown
	}
	copy(log.buf[offset:end], data)

	// Synchronous FastCDC rollup over the entire log buffer.
	s.rollupLocked(log.buf)
	return nil
}

// rollupLocked runs FastCDC over the consolidated payload buffer and
// stores the resulting chunks in the CAS map. Caller MUST hold s.mu
// for write.
func (s *MemoryStore) rollupLocked(buf []byte) {
	if len(buf) == 0 {
		return
	}
	c := chunker.NewChunker()
	pos := 0
	for pos < len(buf) {
		end, _ := c.Next(buf[pos:], true)
		if end <= 0 {
			break
		}
		chunk := buf[pos : pos+end]
		sum := blake3.Sum256(chunk)
		var h blockstore.ContentHash
		copy(h[:], sum[:])
		if _, exists := s.cas[h]; !exists {
			cp := make([]byte, len(chunk))
			copy(cp, chunk)
			s.cas[h] = casEntry{data: cp, lastModified: time.Now()}
		}
		pos += end
	}
}

// DeleteLog removes the per-payload append-log buffer and tombstones
// the payloadID. Already-rolled-up CAS chunks remain in the store —
// orphan-chunk cleanup is GC's responsibility per the contract.
//
// Implements blockstore.BlockStoreAppend.
func (s *MemoryStore) DeleteLog(_ context.Context, payloadID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return ErrStoreClosed
	}
	delete(s.appendLogs, payloadID)
	s.tombstones[payloadID] = struct{}{}
	return nil
}

// WriteAt writes data to the in-memory store at the specified offset.
//
// Deprecated: removed in Phase 18.
func (s *MemoryStore) WriteAt(_ context.Context, payloadID string, data []byte, offset uint64) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.closed {
		return ErrStoreClosed
	}

	if len(data) == 0 {
		return nil
	}

	remaining := data
	currentOffset := offset

	for len(remaining) > 0 {
		blockIdx := currentOffset / blockstore.BlockSize
		blockOffset := uint32(currentOffset % blockstore.BlockSize)

		spaceInBlock := uint32(blockstore.BlockSize) - blockOffset
		writeLen := min(uint32(len(remaining)), spaceInBlock)

		key := memBlockKey(payloadID, blockIdx)
		mb, ok := s.blocks[key]
		if !ok {
			mb = &memBlock{
				data:  make([]byte, blockstore.BlockSize),
				state: blockstore.BlockStatePending,
			}
			s.blocks[key] = mb
		}

		copy(mb.data[blockOffset:blockOffset+writeLen], remaining[:writeLen])
		end := blockOffset + writeLen
		if end > mb.dataSize {
			mb.dataSize = end
		}
		mb.dirty = true

		remaining = remaining[writeLen:]
		currentOffset += uint64(writeLen)
	}

	// Update file size
	end := offset + uint64(len(data))
	if end > s.files[payloadID] {
		s.files[payloadID] = end
	}

	return nil
}

// WriteFromRemote stores data fetched from the remote block store.
// The block is marked Remote since it already exists remotely.
//
// Deprecated: removed in Phase 18.
func (s *MemoryStore) WriteFromRemote(_ context.Context, payloadID string, data []byte, offset uint64) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.closed {
		return ErrStoreClosed
	}

	blockIdx := offset / blockstore.BlockSize
	key := memBlockKey(payloadID, blockIdx)

	mb := &memBlock{
		data:     make([]byte, blockstore.BlockSize),
		dataSize: uint32(len(data)),
		dirty:    false,
		state:    blockstore.BlockStateRemote,
	}
	copy(mb.data, data)
	s.blocks[key] = mb

	end := offset + uint64(len(data))
	if end > s.files[payloadID] {
		s.files[payloadID] = end
	}

	return nil
}

// Flush marks all dirty blocks for a file as Local (flushed).
// In the memory store, there is no disk to flush to -- this just transitions state.
//
// Deprecated: removed in Phase 18.
func (s *MemoryStore) Flush(_ context.Context, payloadID string) ([]local.FlushedBlock, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.closed {
		return nil, ErrStoreClosed
	}

	var flushed []local.FlushedBlock

	for key, mb := range s.blocks {
		if !keyBelongsToFile(key, payloadID) {
			continue
		}
		if mb.dirty {
			mb.dirty = false
			if mb.state == blockstore.BlockStatePending {
				mb.state = blockstore.BlockStatePending
			}
			blockIdx := parseBlockIdx(key, payloadID)
			flushed = append(flushed, local.FlushedBlock{
				BlockIndex: blockIdx,
				LocalPath:  key, // Use key as path in memory store
				DataSize:   mb.dataSize,
			})
		}
	}

	return flushed, nil
}

// SyncFileBlocks is a no-op in the memory store (no persistent store to sync to).
func (s *MemoryStore) SyncFileBlocks(_ context.Context) {}

// SyncFileBlocksForFile is a no-op in the memory store.
func (s *MemoryStore) SyncFileBlocksForFile(_ context.Context, _ string) {}

// Start is a no-op in the memory store (no background goroutines needed).
func (s *MemoryStore) Start(_ context.Context) {}

// Close marks the store as closed.
func (s *MemoryStore) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.closed = true
	return nil
}

// Truncate discards blocks beyond newSize.
func (s *MemoryStore) Truncate(_ context.Context, payloadID string, newSize uint64) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.closed {
		return ErrStoreClosed
	}

	// Remove blocks beyond newSize
	for key := range s.blocks {
		if !keyBelongsToFile(key, payloadID) {
			continue
		}
		blockIdx := parseBlockIdx(key, payloadID)
		if blockIdx*blockstore.BlockSize >= newSize {
			delete(s.blocks, key)
		}
	}

	s.files[payloadID] = newSize
	return nil
}

// EvictMemory removes all data for a file.
func (s *MemoryStore) EvictMemory(_ context.Context, payloadID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	for key := range s.blocks {
		if keyBelongsToFile(key, payloadID) {
			delete(s.blocks, key)
		}
	}
	delete(s.files, payloadID)
	return nil
}

// DeleteAllBlockFiles removes all blocks for a file.
//
// Deprecated: removed in Phase 18.
func (s *MemoryStore) DeleteAllBlockFiles(_ context.Context, payloadID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	for key := range s.blocks {
		if keyBelongsToFile(key, payloadID) {
			delete(s.blocks, key)
		}
	}
	delete(s.files, payloadID)
	return nil
}

// SetEvictionEnabled controls whether eviction is enabled (no-op effect in memory store).
func (s *MemoryStore) SetEvictionEnabled(enabled bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.evictionEnabled = enabled
}

// SetRetentionPolicy is a no-op in the memory store (memory store doesn't do eviction).
func (s *MemoryStore) SetRetentionPolicy(_ blockstore.RetentionPolicy, _ time.Duration) {}

// Stats returns local store statistics.
func (s *MemoryStore) Stats() local.Stats {
	s.mu.RLock()
	defer s.mu.RUnlock()

	var memUsed int64
	var memBlockCount int
	for _, mb := range s.blocks {
		if mb.data != nil {
			memBlockCount++
			memUsed += int64(blockstore.BlockSize)
		}
	}

	return local.Stats{
		FileCount:     len(s.files),
		MemBlockCount: memBlockCount,
		MemUsed:       memUsed,
	}
}

// ListFiles returns the payloadIDs of all tracked files.
func (s *MemoryStore) ListFiles() []string {
	s.mu.RLock()
	defer s.mu.RUnlock()

	result := make([]string, 0, len(s.files))
	for payloadID := range s.files {
		result = append(result, payloadID)
	}
	return result
}

// GetStoredFileSize returns the total stored data size for a file.
func (s *MemoryStore) GetStoredFileSize(_ context.Context, payloadID string) (uint64, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	var total uint64
	for key, mb := range s.blocks {
		if keyBelongsToFile(key, payloadID) {
			total += uint64(mb.dataSize)
		}
	}
	return total, nil
}

