package parity

import (
	"context"
	"math/rand/v2"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/marmos91/dittofs/bench/blockstore"
	"github.com/marmos91/dittofs/pkg/block/engine"
	remotememory "github.com/marmos91/dittofs/pkg/block/remote/memory"
	"github.com/marmos91/dittofs/pkg/metrics"
)

func TestOptsValidateDefaults(t *testing.T) {
	o := Opts{}
	if err := o.Validate(); err != nil {
		t.Fatal(err)
	}
	if len(o.Conc) != 4 || o.Conc[3] != 64 {
		t.Fatalf("default conc sweep = %v", o.Conc)
	}
	if len(o.Quadrants) != len(AllQuadrants) {
		t.Fatalf("default quadrants = %v", o.Quadrants)
	}
	if o.LargeFileBytes != 1<<30 || o.SmallFileBytes != 64<<10 {
		t.Fatalf("default sizes = %d/%d", o.LargeFileBytes, o.SmallFileBytes)
	}
}

func TestOptsValidateRejects(t *testing.T) {
	for _, o := range []Opts{
		{Conc: []int{0}},
		{Conc: []int{999}},
		{Quadrants: []string{"sideways"}},
		{Tools: []string{"scp"}},
	} {
		if err := o.Validate(); err == nil {
			t.Fatalf("Validate(%+v) accepted invalid opts", o)
		}
	}
}

// TestDatasetDeterminism proves the staged (rclone) dataset and the engine
// (dittofs) writer produce identical bytes for the same seed — the
// apples-to-apples guarantee.
func TestDatasetDeterminism(t *testing.T) {
	dir := t.TempDir()
	const size, count = 12345, 3
	if err := stageDataset(dir, "small", count, size, 42); err != nil {
		t.Fatal(err)
	}
	// Regenerate the same file the way writePayload does and compare.
	for i := 0; i < count; i++ {
		disk, err := os.ReadFile(filepath.Join(dir, fileName(i)))
		if err != nil {
			t.Fatal(err)
		}
		rng := rand.NewPCG(fileSeed(42, "small", i), uint64(size))
		mem := make([]byte, size)
		fillDeterministic(rng, mem)
		if string(disk) != string(mem) {
			t.Fatalf("file %d: staged bytes differ from generated bytes", i)
		}
	}
	// Staging is idempotent: a second call must not rewrite.
	st0, _ := os.Stat(filepath.Join(dir, fileName(0)))
	if err := stageDataset(dir, "small", count, size, 42); err != nil {
		t.Fatal(err)
	}
	st1, _ := os.Stat(filepath.Join(dir, fileName(0)))
	if !st0.ModTime().Equal(st1.ModTime()) {
		t.Fatal("stageDataset rewrote an existing complete file")
	}
}

// TestDittofsCells_MemoryRemote runs the upload and cold-restart download
// cells against an in-memory remote: validates the engine plumbing end-to-end
// (write → carve → drain → cold read-through) and that the carve/packed-blocks
// path is the one being measured.
func TestDittofsCells_MemoryRemote(t *testing.T) {
	ctx := context.Background()
	remoteStore := remotememory.New()
	cfg := engine.DefaultConfig()
	cfg.ParallelUploads = 2

	upMx := metrics.New("test", "test")
	bs, ms, cleanup, err := blockstore.NewEngineWithOpts(t.TempDir(), remoteStore, blockstore.EngineOpts{
		Syncer: &cfg, Metrics: upMx, KeepRemoteOpen: true, PackedBlocks: true,
	})
	if err != nil {
		t.Fatal(err)
	}

	opts := Opts{Sample: 50 * time.Millisecond}
	cl := sizeClass{name: "small", fileBytes: 32 << 10, fileCount: 6,
		uploadQ: QuadUploadSmall, downloadQ: QuadDownloadSmall}

	up, upTL, err := dittofsUploadCell(ctx, opts, bs, remoteStore, upMx, cl, 2)
	cleanup()
	if err != nil {
		t.Fatal(err)
	}
	if want := cl.fileBytes * int64(cl.fileCount); up.Bytes != want {
		t.Fatalf("upload bytes = %d, want %d", up.Bytes, want)
	}
	if up.Objects == 0 {
		t.Fatal("upload produced no remote objects — drain did not run")
	}
	_, blocks := countRemoteObjects(ctx, remoteStore)
	if blocks == 0 {
		t.Fatal("no packed-block objects on the remote — carve path not active; " +
			"the harness would be measuring the legacy standalone-CAS mirror")
	}
	if len(upTL.Points) == 0 {
		t.Fatal("upload timeline captured no gauge samples")
	}

	// Cold-restart engine: same metadata, empty local dir, same remote.
	downMx := metrics.New("test", "test")
	bs2, _, cleanup2, err := blockstore.NewEngineWithOpts(t.TempDir(), remoteStore, blockstore.EngineOpts{
		Syncer: &cfg, Metrics: downMx, Metadata: ms, KeepRemoteOpen: true, PackedBlocks: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup2()

	down, _, err := dittofsDownloadCell(ctx, opts, bs2, downMx, cl, 2)
	if err != nil {
		t.Fatal(err)
	}
	if down.Bytes != up.Bytes {
		t.Fatalf("download bytes = %d, want %d", down.Bytes, up.Bytes)
	}
	if down.RemoteReadBytes == 0 {
		t.Fatal("download served 0 bytes from packed blocks — the cold engine did not use the remote read-through path")
	}
	// Byte-integrity: the cold read-through must return the exact generated
	// bytes (readPayload already verified lengths; verify content of file 0).
	buf := make([]byte, cl.fileBytes)
	if _, err := bs2.ReadAt(ctx, payloadID(cl.name, 0), nil, buf, 0); err != nil {
		t.Fatal(err)
	}
	rng := rand.NewPCG(fileSeed(opts.Seed, cl.name, 0), uint64(cl.fileBytes))
	want := make([]byte, cl.fileBytes)
	fillDeterministic(rng, want)
	if string(buf) != string(want) {
		t.Fatal("cold read-through returned different bytes than were written")
	}
}

func TestScorecardMarkdown(t *testing.T) {
	run := &Run{
		Label:     "unit",
		StartedAt: time.Date(2026, 7, 3, 10, 0, 0, 0, time.UTC),
		Opts:      RunOpts{LargeFileBytes: 1 << 30, LargeFileCount: 4, SmallFileBytes: 64 << 10, SmallFileCount: 2048},
		Cells: []Cell{
			{Tool: ToolDittofs, Quadrant: QuadUploadLarge, Conc: 64, ThroughputMbps: 337},
			{Tool: ToolRclone, Quadrant: QuadUploadLarge, Conc: 64, ThroughputMbps: 402},
			{Tool: ToolDittofs, Quadrant: QuadMeta, Conc: 8, OpsPerSec: 120, Objects: 30},
			{Tool: ToolRclone, Quadrant: QuadMeta, Conc: 8, OpsPerSec: 240, Objects: 2048},
		},
	}
	md := Scorecard(run)
	for _, want := range []string{
		"## upload-large",
		"| 64 | 337.0 | 402.0 | 84% |",
		"## meta",
		"| 8 | 120.0 | 240.0 | 50% |",
	} {
		if !strings.Contains(md, want) {
			t.Fatalf("scorecard missing %q:\n%s", want, md)
		}
	}
	// download-large has no cells: no empty table.
	if strings.Contains(md, "## download-large") {
		t.Fatal("scorecard rendered an empty quadrant table")
	}
}

func TestCellsCSV(t *testing.T) {
	csvOut := cellsCSV([]Cell{{Tool: "dittofs", Quadrant: QuadUploadLarge, Conc: 8, Files: 4, Bytes: 1024, Seconds: 2, ThroughputMbps: 0.004}})
	lines := strings.Split(strings.TrimSpace(csvOut), "\n")
	if len(lines) != 2 {
		t.Fatalf("csv lines = %d, want 2:\n%s", len(lines), csvOut)
	}
	if !strings.HasPrefix(lines[1], "dittofs,upload-large,8,4,1024,") {
		t.Fatalf("csv row = %s", lines[1])
	}
}

func TestS3ConfigFromEnvFailsFast(t *testing.T) {
	for _, k := range []string{"AWS_S3_BUCKET", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_ENDPOINT_URL", "AWS_S3_REGION", "AWS_S3_PATH_STYLE", "AWS_S3_KEY_PREFIX"} {
		t.Setenv(k, "")
		_ = os.Unsetenv(k)
	}
	_, err := s3ConfigFromEnv()
	if err == nil {
		t.Fatal("expected error with no env")
	}
	for _, want := range []string{"AWS_S3_BUCKET", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("error %q does not name missing var %s", err, want)
		}
	}
}
